const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('C:/Users/Sherwin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1669,height:940},acceptDownloads:true});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://localhost:3000');
  await page.waitForSelector('#starter-actions');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#document-title').inputValue(),'Untitled document');
  assert.equal((await page.locator('#editor').innerText()).trim(),'');
  assert(await page.evaluate(()=>document.fonts.check('20px MaterialSymbols')));
  const invalidIcons=await page.evaluate(()=>{const ctx=document.createElement('canvas').getContext('2d');ctx.font='20px MaterialSymbols';return [...document.querySelectorAll('.material-symbol')].map(el=>el.textContent).filter(name=>ctx.measureText(name).width>25);});
  assert.deepEqual(invalidIcons,[],'Every toolbar icon must resolve to an actual Material Symbol');
  assert(await page.locator('.side-rail img').evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth>0)));
  await page.screenshot({path:'artifacts/desktop.png',fullPage:false});
  await page.locator('#editor').click();
  await page.keyboard.type('A saved first draft.');
  assert(!(await page.locator('#starter-actions').isVisible()));
  await page.waitForTimeout(800);
  await page.reload();
  assert.match(await page.locator('#editor').innerText(),/A saved first draft/);
  await page.locator('#menus button').first().click();
  await page.locator('#menu-popup').getByText('New document',{exact:true}).click();
  assert(await page.locator('#starter-actions').isVisible());
  await page.locator('#docs-home').click();
  await page.locator('.document-row').first().click();
  assert.match(await page.locator('#editor').innerText(),/A saved first draft/);
  await page.locator('#menus button').first().click();
  await page.locator('#menu-popup').getByText('New document',{exact:true}).click();
  await page.locator('[data-starter="templates"]').click();
  await page.getByRole('button',{name:'Product strategy',exact:true}).click();
  assert.match(await page.locator('#editor').innerText(),/Building what’s next/);
  await page.locator('#document-title').fill('Launch plan');
  await page.locator('#editor h2').first().click();
  await page.evaluate(()=>{const p=document.querySelector('#editor p:not(.document-subtitle)');const node=p.firstChild;const range=document.createRange();range.setStart(node,0);range.setEnd(node,5);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);});
  await page.locator('[data-command="bold"]').click();
  assert.match(await page.locator('#editor').innerHTML(),/strong|<b>/i);
  await page.locator('#editor').press('End');
  await page.locator('#editor').press('Enter');
  await page.keyboard.type('This is a saved line.');
  await page.waitForTimeout(900);
  await page.reload();
  assert.equal(await page.locator('#document-title').inputValue(),'Launch plan');
  assert.match(await page.locator('#editor').innerText(),/This is a saved line/);
  await page.locator('#add-tab').click();
  await page.locator('#editor').fill('Second tab content');
  await page.evaluate(()=>{const node=document.querySelector('#editor').firstChild;const range=document.createRange();range.selectNodeContents(node);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);});
  await page.locator('#block').selectOption('h2');
  assert.match(await page.locator('#outline').innerText(),/Second tab content/);
  await page.evaluate(()=>{const node=document.querySelector('#editor h2').firstChild;const range=document.createRange();range.selectNodeContents(node);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);});
  await page.locator('#link').click();
  await page.locator('#dialog-content label').last().locator('input').fill('https://example.com');
  await page.locator('#dialog-content .primary-button').click();
  assert.match(await page.locator('#editor a').getAttribute('href'),/^https:\/\/example\.com\/?$/);
  await page.locator('#add-comment').click();
  await page.locator('#comment-text').fill('Review this section');
  await page.locator('#comment-form button').click();
  assert.match(await page.locator('#comment-list').innerText(),/Review this section/);
  await page.waitForTimeout(900);
  await page.reload();
  assert.match(await page.locator('#editor').innerText(),/Second tab content/);
  assert.match(await page.locator('#comment-list').innerText(),/Review this section/);
  await page.locator('.document-tab').first().click();
  assert.match(await page.locator('#editor').innerText(),/Building what’s next/);
  await page.locator('#menus button').first().click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByText('Download as HTML').click();
  const download=await downloadPromise;
  assert.equal(download.suggestedFilename(),'Launch plan.html');
  await page.locator('#add-tab').click();
  await page.locator('#editor').fill('Accurate formatting');
  const selectEditor=()=>page.evaluate(()=>{const editor=document.querySelector('#editor');editor.focus();const r=document.createRange();r.selectNodeContents(editor);const s=getSelection();s.removeAllRanges();s.addRange(r);});
  await selectEditor();
  await page.locator('#block').selectOption('p');
  await selectEditor();
  await page.locator('#font-size').fill('18');
  await page.locator('#font-size').press('Tab');
  assert.equal(await page.locator('#editor font').first().evaluate(el=>getComputedStyle(el).fontSize),'24px');
  await selectEditor();
  await page.locator('#text-color-button').click();
  await page.getByRole('button',{name:'Text #cc0000',exact:true}).click();
  assert.match(await page.locator('#editor').innerHTML(),/cc0000|rgb\(204, 0, 0\)/);
  await selectEditor();
  await page.locator('#line-spacing').click();
  await page.locator('#menu-popup').getByText('Double',{exact:true}).click();
  assert.equal(await page.locator('#editor p').evaluate(el=>el.style.lineHeight),'2');
  await page.locator('#alignment').click();
  await page.locator('#menu-popup').getByText('Center align',{exact:true}).click();
  assert.equal(await page.locator('#editor p').evaluate(el=>getComputedStyle(el).textAlign),'center');
  await page.locator('#mode').click();
  await page.locator('#menu-popup').getByText('Viewing',{exact:true}).click();
  assert.equal(await page.locator('#editor').getAttribute('contenteditable'),'false');
  assert(await page.locator('[data-command="bold"]').isDisabled());
  await page.locator('#mode').click();
  await page.locator('#menu-popup').getByText('Editing',{exact:true}).click();
  await page.locator('#find').click();
  await page.getByRole('textbox',{name:'Search the menus',exact:true}).fill('word count');
  await page.locator('.search-results button').click();
  assert.equal(await page.locator('#dialog-title').innerText(),'Word count');
  await page.locator('#dialog-content input[type=checkbox]').check();
  await page.locator('#dialog-content').getByText('OK',{exact:true}).click();
  assert(await page.locator('#word-count').isVisible());
  await page.locator('#menus button').first().click();
  await page.locator('#menu-popup').getByText('Page setup',{exact:true}).click();
  await page.locator('#dialog-content select').nth(1).selectOption('A4');
  await page.locator('#dialog-content input[type=number]').fill('0.75');
  await page.locator('#dialog-content').getByText('OK',{exact:true}).click();
  await page.waitForTimeout(800);
  await page.reload();
  assert.equal(await page.locator('#editor').evaluate(el=>getComputedStyle(el).paddingLeft),'72px');
  assert.equal(await page.locator('#editor').evaluate(el=>getComputedStyle(el).width),'794px');
  await page.keyboard.press('Control+Shift+f');
  assert.equal(await page.locator('.find-bar').count(),0);
  assert(!(await page.locator('.header').isVisible()));
  await page.keyboard.press('Control+Shift+f');
  await page.locator('.document-tab').first().click();
  await page.locator('#notes').click();
  await page.getByRole('textbox',{name:'Document notes'}).fill('Notes stay with this document.');
  await page.locator('#tasks').click();
  await page.getByRole('textbox',{name:'New task'}).fill('Review the draft');
  await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.locator('.task-row input[type=checkbox]').check();
  await page.waitForTimeout(800);
  await page.reload();
  await page.locator('#tasks').click();
  assert(await page.locator('.task-row input[type=checkbox]').isChecked());
  await page.locator('#notes').click();
  assert.equal(await page.getByRole('textbox',{name:'Document notes'}).inputValue(),'Notes stay with this document.');
  await page.locator('#contacts').click();
  await page.getByRole('textbox',{name:'Contact name'}).fill('Test colleague');
  await page.getByRole('textbox',{name:'Contact email'}).fill('colleague@example.com');
  await page.getByRole('button',{name:'Add contact',exact:true}).click();
  assert.match(await page.locator('.contact-card').innerText(),/Test colleague/);
  await page.locator('#calendar').click();
  assert.equal(await page.locator('.calendar-grid button').count()>=28,true);
  await page.locator('#close-utility').click();
  await page.locator('#meet').click();
  assert.equal(await page.locator('#dialog-content a').getAttribute('href'),'https://meet.google.com/');
  await page.locator('#dialog .dialog-heading button').click();
  await page.locator('#add-tab').click();
  await page.locator('#editor').click();
  await page.keyboard.type('Undo this sentence.');
  await page.locator('[data-command="undo"]').click();
  assert((await page.locator('#editor').innerText()).trim().length<'Undo this sentence.'.length);
  await page.locator('[data-command="redo"]').click();
  assert.equal((await page.locator('#editor').innerText()).trim(),'Undo this sentence.');
  await page.locator('#editor').press('End');
  await page.locator('#font-size').fill('24');
  await page.locator('#font-size').press('Tab');
  await page.locator('#editor').focus();
  await page.keyboard.type(' Large text');
  assert(await page.locator('#editor font').evaluateAll(nodes=>nodes.some(el=>el.textContent.includes('Large text')&&getComputedStyle(el).fontSize==='32px')));
  await page.locator('#image-file').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  await page.waitForFunction(()=>!!document.querySelector('#editor img')?.naturalWidth);
  await page.locator('.document-tab').first().click();
  await page.waitForTimeout(3500);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/mobile.png',fullPage:false});
  const menuRows=await page.locator('#menus button').evaluateAll(buttons=>[...new Set(buttons.map(b=>b.getBoundingClientRect().y))]);
  assert.equal(menuRows.length,1,'Mobile menu should stay on one row');
  assert(await page.locator('#editor').isVisible());
  await page.locator('.mobile-outline-button').click();
  assert(await page.locator('.outline-panel').isVisible());
  assert.deepEqual(errors,[]);
  console.log('Passed: official icon glyphs/assets, blank typing, document switching, templates, formatting, font size, colors, spacing, alignment, viewing mode, tool finder, page settings, shortcuts, autosave, tabs, comments, export, notes/tasks persistence, contacts/calendar, service links, and mobile layout.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
